//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerLogs
    {
        public int Id { get; set; }
        public long Imei { get; set; }
        public System.DateTime Date { get; set; }
        public int Longitude { get; set; }
        public int Latitude { get; set; }
    }
}
